export const HOME_PATH = '/';
export const ORGANIZATIONS_PATH = '/organizations';
export const ORGANIZATIONS_DETAILS = '/organizations/show/#/{organizationId}';
// export const ENVELOPES_PATH = "/envelopes" // not used
export const ENVELOPES_DETAILS = '/envelopes/show/#/{nullifier}';
export const PROCESSES_PATH = '/processes';
export const PROCESS_DETAILS = '/processes/show/#/{processId}';
export const BLOCKS_PATH = '/blocks';
export const BLOCKS_DETAILS = '/blocks/show/#/{blockHeight}';
export const TRANSACTIONS_PATH = '/transactions';
export const TRANSACTIONS_DETAILS = '/transactions/show/#/{blockHeight}/{index}';
export const VALIDATORS_PATH = '/validators';
export const STATS_PATH = '/stats';
export const TOOLS_PATH = '/converter';
export const VERIFY = '/verify';
export const VERIFY_DETAILS = '/verify/#/{voteId}';
