export const HOME_PATH = "/"
export const ORGANIZATIONS_PATH = "/organizations"
export const ELECTIONS_PATH = "/elections"
export const BLOCKS_PATH = "/blocks"
export const TRANSACTIONS_PATH = "/transactions"
export const VALIDATORS_PATH = "/validators"
export const STATS_PATH = "/stats"
