---
name: Main

on: [push, pull_request]

jobs:
  node-tests-and-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

  docker-release:
    runs-on: self-hosted
    needs:
      - node-tests-and-build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stg' || startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/wip/mockup'
    steps:
      - uses: AutoModality/action-clean@v1.1.0
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Get branch name, git commit hash and current time in secs
        id: vars
        shell: bash
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )" >> $GITHUB_OUTPUT
          echo "GIT_HASH_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "DATE_IN_SECS=$(date +%s)" >> $GITHUB_OUTPUT
      - name: Push to ghcr.io (dynamic build)
        uses: docker/build-push-action@v4
        if: |
          { % if ( github.ref == 'refs/heads/master' ) % }
          {{
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64
            push: true
            build-args: |
              COMMIT_SHA=${{ steps.vars.outputs.GIT_HASH_SHORT }}
              VOCDONI_ENVIRONMENT=dev
              DISCOVERY_POOL_SIZE=1
              ETH_NETWORK_ID=goerli
            tags: |
              ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}
              ghcr.io/vocdoni/${{ github.event.repository.name }}:commit-${{ steps.vars.outputs.GIT_HASH_SHORT }}
              ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}-${{ steps.vars.outputs.DATE_IN_SECS }}
          }}
          { % elif ( startsWith(github.ref, 'refs/heads/release') ) % }
          {{
          with:
            context: .
              file: ./Dockerfile
              platforms: linux/amd64
              push: true
              build-args: |
                COMMIT_SHA=${{ steps.vars.outputs.GIT_HASH_SHORT }}
                VOCDONI_ENVIRONMENT=prod
                DISCOVERY_POOL_SIZE=1
                ETH_NETWORK_ID=xdai
              tags: |
                ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}
                ghcr.io/vocdoni/${{ github.event.repository.name }}:commit-${{ steps.vars.outputs.GIT_HASH_SHORT }}
                ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}-${{ steps.vars.outputs.DATE_IN_SECS }}
          }}
          { % else % }
          {{
          with:
            context: .
              file: ./Dockerfile
              platforms: linux/amd64
              push: true
              build-args: |
                COMMIT_SHA=${{ steps.vars.outputs.GIT_HASH_SHORT }}
                DISCOVERY_POOL_SIZE=1
                ETH_NETWORK_ID=goerli
              tags: |
                ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}
                ghcr.io/vocdoni/${{ github.event.repository.name }}:commit-${{ steps.vars.outputs.GIT_HASH_SHORT }}
                ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}-${{ steps.vars.outputs.DATE_IN_SECS }}
          }}

      - name: Push to ghcr.io (dynamic build)
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/stg'
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            COMMIT_SHA=${{ steps.vars.outputs.GIT_HASH_SHORT }}
            VOCDONI_ENVIRONMENT=stg
            DISCOVERY_POOL_SIZE=1
            ETH_NETWORK_ID=goerli
            BOOTNODES_URL=https://raw.githubusercontent.com/vocdoni/bootnodes/main/content/gateways.stg.json
          tags: |
            ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}
            ghcr.io/vocdoni/${{ github.event.repository.name }}:commit-${{ steps.vars.outputs.GIT_HASH_SHORT }}
            ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}-${{ steps.vars.outputs.DATE_IN_SECS }}
      - name: Push to ghcr.io (static build)
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release')
        with:
          context: .
          file: ./Dockerfile.static
          platforms: linux/amd64
          push: true
          build-args: |
            COMMIT_SHA=${{ steps.vars.outputs.GIT_HASH_SHORT }}
            DISCOVERY_POOL_SIZE=1
          tags: |
            ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}-static
            ghcr.io/vocdoni/${{ github.event.repository.name }}:commit-${{ steps.vars.outputs.GIT_HASH_SHORT }}
            ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.vars.outputs.BRANCH_NAME }}-static-${{ steps.vars.outputs.DATE_IN_SECS }}
